version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: setup
    ports:
      - '3406:3306'
    volumes:
      - mysql-data:/var/lib/mysql
  app: &app_base
    build: .
    command: >
      bash -c "rm -f tmp/pids/* &&
      rm -f log/development.log &&
      bundle install &&
      rails db:create &&
      rails s"
    volumes:
      - .:/docker-compose-setup
      - public-data:/docker-compose-setup/public
      - tmp-data:/docker-compose-setup/tmp
      - log-data:/docker-compose-setup/log
    depends_on:
      - db
    stdin_open: true
    tty: true
  webpacker:
    <<: *app_base
    command: >
      bash -c "yarn install && bundle install && bin/webpack-dev-server"
    ports:
      - '3035:3035'
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    depends_on:
      - app
  web:
    build:
      context: nginx
    volumes:
      - public-data:/docker-compose-setup/public
      - tmp-data:/docker-compose-setup/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  mysql-data:
  public-data:
  tmp-data:
  log-data:
